---
fixtures:
  repositories:
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core
    epel: https://github.com/voxpupuli/puppet-epel
    nginx: https://github.com/voxpupuli/puppet-nginx
    nodejs: https://github.com/voxpupuli/puppet-nodejs
    python: https://github.com/voxpupuli/puppet-python
    redis: https://github.com/voxpupuli/puppet-redis
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    systemd: https://github.com/voxpupuli/puppet-systemd
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
